segment_vars:
    - "Federal Poverty Level"
    - "Geometry Floor Area Bin"
    - "Geometry Building Type RECS"
    - "Vintage"
    - "Heating Fuel"
    - "Sampling Region"

segment_selection_sample_size: 10000000  # Determine segments using 10M samples
num_samples_per_segment: 12