EIA_MONTHLY_ELECTRICITY = "s3://resstock-core/truth_data/v01/EIA/eia_processed/electricity_monthly_sales.csv"
EIA_MONTHLY_NATURAL_GAS = "s3://resstock-core/truth_data/v01/EIA/eia_processed/natural_gas_monthly_sales.csv"
EIA_ANNUAL_ELECTRICITY = "s3://resstock-core/truth_data/v01/EIA/eia_processed/electricity_annual_sales.csv"
LRD_2018 = "s3://resstock-core/truth_data/v01/LRD_data/2018_processed_res_lrd_all.csv"
RECS_2020_microdata = "s3://resstock-core/truth_data/v01/RECS/recs_processed/recs_2020_processed_microdata.csv"
RECS_2020_monthly = "s3://resstock-core/truth_data/v01/RECS/recs_processed/recs_2020_monthly_consumption.csv"
