"""
Usually, the values are sorted a hybrid of lexicographic and numeric using
human_sort function in utils.py. However, for some cases, we need to sort
values based on a custom order. This defines the custom sort order."""

custom_sorts: dict[str, list[str]] = {
    "in.geometry_building_type_recs": [
        "Single-Family Detached",
        "Single-Family Attached",
        "Multi-Family 2-4",
        "Multi-Family 5+",
        "Mobile Home",
    ],
    "in.heating_fuel": ["Electricity", "Natural Gas", "Fuel Oil", "Propane", "Wood", "Other Fuel", "None"],
    "in.water_heater_fuel": [
        "Electricity",
        "Natural Gas",
        "Fuel Oil",
        "Propane",
        "Wood",
        "Other Fuel",
        "Solar Thermal",
        "None",
    ],
    "in.building_america_climate_zone": [
        "Hot-Dry",
        "Hot-Humid",
        "Mixed-Dry",
        "Mixed-Humid",
        "Marine",
        "Cold",
        "Very Cold",
        "Subarctic",
    ],
    "in.usage_level": [
        "Low",
        "Medium",
        "High",
    ],
    "in.water_heater_efficiency": [
        "Electric Standard",
        "Electric Premium",
        "Electric Tankless",
        "Electric Heat Pump, 50 gal, 3.45 UEF",
        "Natural Gas Standard",
        "Natural Gas Premium",
        "Natural Gas Tankless",
        "Fuel Oil Standard",
        "Fuel Oil Premium",
        "FIXME Fuel Oil Indirect",
        "Propane Standard",
        "Propane Premium",
        "Propane Tankless",
        "Solar Thermal, 40 sqft, East, Roof Pitch, Electric Standard Backup",
        "Solar Thermal, 40 sqft, North, Roof Pitch, Electric Standard Backup",
        "Solar Thermal, 40 sqft, South, Roof Pitch, Electric Standard Backup",
        "Solar Thermal, 40 sqft, South, Roof Pitch, Natural Gas Standard Backup",
        "Solar Thermal, 40 sqft, South, Roof Pitch, Fuel Oil Standard Backup",
        "Solar Thermal, 40 sqft, South, Roof Pitch, Propane Standard Backup",
        "Solar Thermal, 40 sqft, West, Roof Pitch, Electric Standard Backup",
        "Wood",
        "Other Fuel",
        "None",
    ],
    "in.water_heater_location": [
        "Living Space",
        "Conditioned Mechanical Room",
        "Heated Basement",
        "Unheated Basement",
        "Garage",
        "Attic",
        "Crawlspace",
        "Outside",
    ],
    "in.windows": [
        "Single, Clear, Metal",
        "Single, Clear, Metal, Exterior Clear Storm",
        "Single, Clear, Non-metal",
        "Single, Clear, Non-metal, Exterior Clear Storm",
        "Double, Clear, Metal, Air",
        "Double, Clear, Metal, Air, Exterior Clear Storm",
        "Double, Clear, Non-metal, Air",
        "Double, Clear, Non-metal, Air, Exterior Clear Storm",
        "Double, Low-E, Non-metal, Air, M-Gain",
        "Triple, Low-E, Non-metal, Air, L-Gain",
    ],
}
keep_last_keys = [
    "None",
    "No",
    "Never",
    "Not Available",
    "No Constraint"
]
